### ISSUE TITLE
The default map, whole-keyboard capture, and quit and suspend under raw mode

### ISSUE THREAD

**Issue by paulchiu** [paulchiu/repon#46]
## What to build

The full default keyboard works, typing into a filter or a palette cannot trigger a command, and quit and suspend behave correctly even though raw mode has cleared the terminal driver's own handling of them.

## Acceptance criteria

- [ ] Key matching handles the terminal library's semantics: an uppercase letter arrives with the shift modifier set, a control chord arrives lowercase with control, release events are filtered before dispatch, and the control-plus-shift-plus-letter form is not used because most terminals cannot distinguish it.
- [ ] Three control chords are permanently unbindable in the default map and via user config alike, because different terminals deliver them as different logical keys.
- [ ] Quit and suspend are implemented as ordinary key handlers rather than relying on signal delivery, because raw mode clears the signal-generating flag.

## Design this makes true

Covers 0 recorded design requirements, one of 62 tickets covering the whole terminal interface.

## Blocked by

- #34 (The tracer: real rows on screen, one Snapshot per frame)
- #40 (One compiled binding table across six contexts)

**Comment by paulchiu** [comment]
Closed by `9cf0c8f` (implementation) and `fde76c5` (review follow-up), merged to `main`.

## Most of this ticket was already true, and that was worth checking

The implementing agent reported that the binding table's landing had already satisfied the release-event filter and the quit/suspend wiring, so its real contribution was the tests that pin them plus enforcement of the unbindable chords. I verified that against the parent commit rather than taking it: `translate`'s `KeyEventKind::Press` guard and the `Action::Quit`/`Action::Suspend` routing both genuinely pre-existed.

## The defect that mattered: suspend could hand back a broken terminal

`Tui::suspend` calls `self.exit()` and then raises `SIGTSTP`. I swapped those two lines and **all 96 tests passed**. Ctrl+Z would then stop the process while still in raw mode on the alternate screen, dropping the user into their shell with a broken terminal. That is precisely the failure criterion 3 names, and the reason it insists quit and suspend be ordinary key handlers rather than signal delivery: raw mode clears the signal-generating flag.

The first pass declined to test this, citing the standing rule against entering raw mode in a test and a prior 45-minute hang. That reasoning was sound but stopped one step short: the repository already had the escape hatch, a pty-driven subprocess harness plus a debug-only flag that calls `tui.enter()` without touching `Config` or `Core`. An analogous `--suspend-after-tui-enter` through the same harness proves the ordering with no test process ever entering raw mode. It fails in under a second, with the evidence being the pty output holding only the enter sequence:

```
the terminal must be restored before the process stops, but no LeaveAlternateScreen
appeared in the output collected while it was stopped:
"\u{1b}[?1049h\u{1b}[?2004h ... \u{1b}[?25l"
```

That test needed one more fix after merging, recorded in `b2eeef8`: it passed alone and failed under a full run, because the child inherited the test runner's process group and POSIX discards `SIGTSTP` sent to an orphaned process group. Whether the child stopped depended on ancestry above cargo rather than anything the test controlled. It now gets its own process group in the same session.

## A guarantee that had quietly weakened

To admit the new test's `KeyEvent::new(...)`, `no_key_literal_is_written_outside_this_table` had been widened to exempt the whole of `tui.rs`. A reviewer put a real, non-test `KeyCode::Char('x')` with `CONTROL` into `tui.rs`'s production `translate`, a hidden binding bypassing `dispatch` entirely, and the test still passed, while its own doc comment continued to claim this module is the only place such a literal may appear.

The exemption is now scoped to the trailing `#[cfg(test)] mod tests` module, matching the fix a sibling ticket needed for the same class of bug. A production key literal in `tui.rs` is caught again, naming the offending lines.

## A runtime check moved to compile time

`PERMANENTLY_UNBINDABLE` was enforced inside `lookup`, rescanning on every keystroke to guard a condition that is fixed at compile time and that CI already made impossible in a shipped binary. The crate already had the right idiom in `glyphs.rs`. A banned chord in the table is now a build failure:

```
error[E0080]: evaluation panicked: the default map binds a permanently unbindable chord
```

The runtime scan and the two tests that duplicated what the assertion now proves are gone.

## Recorded

- The three chords match `docs/spec/keybindings.md` exactly, no more and no fewer, proven by mutation.
- Criterion 1 is fully covered: crossterm 0.29 defines exactly three `KeyEventKind` variants and the filter test exercises all three, including `Repeat`.
- The "and via user config alike" half of criterion 2 is met only for the default map, because no config merge exists yet to enforce it against. The list is shaped for that ticket to consume rather than restate.

`just ci` and `just publish-check` green on `main` after merge.
