### ISSUE TITLE
Provenance renders: the row fold, the gutter, blank cells, one cell-to-render mapping

### ISSUE THREAD

**Issue by paulchiu** [paulchiu/repon#37]
## What to build

The screen stops being able to lie: the core folds each row to one summary state, an uncomputed count renders blank with a mark rather than as zero, and every row carries one character saying how much of it to trust.

## Acceptance criteria

- [ ] One rendering function turns a cell into text plus a gutter mark and every column widget calls it; there is no just-show-the-number path anywhere and no wildcard or default match arm on that path.
- [ ] The mapping is exactly: known and fresh renders the value behind a blank gutter; known and stale renders the value with the stale mark; unknown renders blank with the unknown mark; failed renders blank with the failed mark; Not-applicable renders blank and is excluded from the summary; nothing settled while in flight renders blank with the loading mark.
- [ ] A blank cell means no value here and the gutter says why; no glyph is drawn in a value cell for a provenance state.
- [ ] No numeric-bearing cell can render a raw numeric default: an uncomputed ahead, behind, base or changed-file count reads unknown, proven by a test.
- [ ] The gutter carries the row's least-settled state using the active table's gutter glyphs, and turning the core's row summary into a character happens here on the consumer side, never in the core.
- [ ] A cell being re-probed keeps showing its previous value rather than reverting to blank.
- [ ] The fold returns an enum, never a glyph; mapping it to a character is explicitly the consumer's job.
- [ ] In-flight outranks the least-settled summary; Not-applicable cells are excluded from the fold entirely; otherwise the least-settled state present wins.
- [ ] A failing entity-level derivation drives the row to failed even when every cell is fine, and the fold also reads the last run's result so a failed step does the same.
- [ ] The default branch's rung and any rung disagreement stay out of the fold, being metadata about how a value was obtained rather than values that can fail.
- [ ] Tests cover a Repo row whose state cell is Not-applicable and a detached row whose state cell is Not-applicable, both folding to fresh rather than unknown, since the gutter summarises provenance and not completeness.

## Design this makes true

ADR 0001, 0010, 0017, 0019  ·  `docs/spec/core-api.md`, `docs/spec/layout-and-provenance.md`

Covers 11 recorded design requirements, one of 62 tickets covering the whole terminal interface.

## Blocked by

- #27 (The table: an entity's state and the Snapshot a consumer reads)
- #34 (The tracer: real rows on screen, one Snapshot per frame)

**Comment by paulchiu** [comment]
Carried over from #31, so it is not lost.

A `.gitmodules` read failure is captured and tested: it lands on the parent's `Diagnostics.gitmodules_failed`, plumbed through `Core` and covered by `an_unparseable_gitmodules_file_is_reported_as_a_failure_with_no_submodule_rows`. What is not done is surfacing it in the gutter.

discovery.md describes that failure as the first row-summary input that is not a Cell, which makes it an amendment to ADR 0010's fold rather than a small addition, since `summary()` currently folds Cells only. #31 cut it deliberately rather than freelance a change to the fold.

This ticket owns the row fold and the gutter, so wire it here: a parent whose `.gitmodules` could not be read should mark its row, and the fold needs to accept an input that is not a Cell without weakening the Not-applicable exclusion or the in-flight precedence that #27's tests pin down.

**Comment by paulchiu** [comment]
Closed by `600a1ea` (implementation) and `70c49ca` (review follow-up), merged to `main`.

## The behavioural defect the review caught

`summary()` returned `RowSummary::InFlight` whenever any cell was in flight. `docs/spec/refresh.md`, under "What the gutter and the cells show", is more specific:

> In-flight is a row property that outranks the least-settled-state summary. While a row holds no values at all, its first probe, the spinner sits in the gutter, one moving character per row. Once the row holds some values and only some cells are outstanding, the spinner sits in those cells and the gutter shows the row's least-settled settled state.

ADR 0010's "Amended by 0013" says the same. This ticket's criterion "In-flight outranks the least-settled summary" is a compressed restatement of that topic sentence, and the spec's two-case refinement governs it. The first pass implemented the summary of the rule instead of the rule, and two new tests asserted the wrong half, which would have locked it in.

This matters because `refresh.md` records the predecessor's defect as a 4.02 second refresh sampled 55 times with not one spinner frame on any row. An unconditional `InFlight` is the mirror image: a gutter that spins forever and never falls back to what the row actually knows.

`InFlight` now fires only while the row holds no values at all. Reverting the guard fails two tests with `left: InFlight, right: Failed`.

### The edge case, decided from the spec

A row whose only settled cells are `Not-applicable` counts as holding no values, so it still shows the first-probe spinner. The alternative would make a freshly constructed Submodule, whose `state` and `base` are `Not-applicable` from construction, skip the spinner entirely and jump to `Unknown` the instant any cell begins probing, which reproduces the static screen the rewrite exists to fix. Covered by its own test.

## The recurring defect species, closed twice more

This project keeps hand-enumerating `EntityState`'s cells instead of destructuring them once, and every site is silently wrong when a cell is added. Proven here: adding a seventh `Cell` and settling it to `Failed` made `summary()` return `Fresh`, a row showing a clean gutter while carrying a failed probe, which is the exact lie this ticket exists to prevent.

Both the fold and `derivation_failed` now destructure exhaustively, as does `Diagnostics` and `ActionRun`. After merging, adding a seventh cell produces two compile errors at once:

```
error[E0027]: pattern does not mention field `merge_probe`
   --> crates/repon-core/src/entity.rs:263:13
error[E0027]: pattern does not mention field `merge_probe`
   --> crates/repon-core/src/snapshot.rs:94:9
```

The remaining site is `sweep_deadline`, which #36 extended to hand-list three cells. It is tracked there.

## Two more gaps the review found

- **No test ever passed a non-default glyph set.** `FULL` and `ASCII` share identical characters for fresh, stale, unknown and failed, differing only in the spinner, so hardcoding four of the five arms as literals passed the entire suite. Now covered against the ASCII table.
- **The `Settledness` order was never proven total.** No test put an `Unknown` cell and a `Failed` cell on the same entity, so swapping their declaration order passed all 15 snapshot tests. All 4x4 ordered pairs are now exercised.

## Recorded, not built

- `ActionRun.failed` is read by the fold, as criterion 9 requires, but nothing outside a test writes `last_action`. Its doc comment now says so plainly, and notes that `docs/spec/actions.md` already fixes a richer receipt under the name `ActionReceipt` with `label`, `steps`, `not_applicable` and `finished_at`. Whoever builds the fan-out reconciles the two; no receipt was invented here.
- `Diagnostics`' doc claimed its fields stay out of the fold, which this work made false for `gitmodules_failed`. Corrected.
- Drawing a spinner inside a value cell remains progressive fill's concern. Only the gutter's fallback was in scope here, and that half was not deferrable, because it is row-summary logic.

`just ci` and `just publish-check` green on `main` after merge: 87 tests in repon, 122 in repon-core.
